### ISSUE TITLE
Some social icons are smaller

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#100]
Found at the bottom of https://betaweb.weblate.org/en/download/

![bilde](https://user-images.githubusercontent.com/13802408/61787827-e1a66900-ae10-11e9-8329-d1b9245c7a90.png)

The f is one pixel short at either side.

The GitHub logo is two pixels short at the top side, and just 1px at the bottom, (but looks like two because it is open ended.)

![bilde](https://user-images.githubusercontent.com/13802408/61788055-6b563680-ae11-11e9-9120-94fdd270516e.png)

**Comment by nijel** [comment]
Should be fixed now.

**Comment by comradekingu** [comment]
I would say the f is one pixel short still on both sides

![bilde](https://user-images.githubusercontent.com/13802408/61795157-0d324f00-ae23-11e9-8ea6-093043bb681e.png)

if you squint it makes it clear. The f is a less dominant shape, so it is more pronounced, going a bit over with the shadow is not a problem.

**Comment by nijel** [comment]
What browser is that? It looks okay to me in Firefox 67.

**Comment by nijel** [comment]
Okay, it's probably Chrome, it seems to render SVG slightly differently than Firefox....
