### ISSUE TITLE
RTL images broken

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/website#110]
Some images are wrongly displayed in RTL mode - the rounded corners are on wrong side and logo or avatar are on screen side instead of center. Mostly on https://weblate.org/ar/donate/ and https://weblate.org/ar/about/.

Possible fixes:

* apply CSS transform
* use original images and place them using CSS

**Comment by nijel** [comment]
English:

![Screenshot_2019-10-11 The Weblate Way](https://user-images.githubusercontent.com/212189/66681789-c3b00e00-ec73-11e9-91a0-b0cfae35d924.png)

Arabic:

![Screenshot_2019-10-11 طريقة Weblate](https://user-images.githubusercontent.com/212189/66681801-c874c200-ec73-11e9-939d-a0e4499e44ab.png)

**Comment by kamransarwar** [comment]
![image](https://user-images.githubusercontent.com/5537822/67377972-ee696300-f59f-11e9-939e-8f05389b8bfe.png)

I've fixed the CSS issue and generated the pull request. Please review.
