### ISSUE TITLE
Changes on FR and ES pages not showing up

### ISSUE THREAD

**Issue by khalidbelk** [WeblateOrg/website#1526]
### Describe the issue

Hi 🙂, as you can see in the screenshots below, the FR **(1)** and ES **(2)** websites need some changes which I found out it was some mistakes made by other translators 

- For the FR website they unnecessarily added the & nbsp; in plain text (fixed - see commit b220260196665784b55163e335e0547cadd031d4)

- For the ES website the order of currency and price are wrong (fixed - see commit dfdfbe1f4850b53b763ef85c2dd5025165e90c86) 

The problem is that I'm not seeing the changes on the website 2 days after the fixes, so it is because they've to be manually updated (I don't think this is the reason 😅) or I didn't translate in the right page (I tried to see to which html page the translations belong to and they seem to be correct to me). I would like to know, thank you in advance :)

**(1)**
<img width="787" alt="image" src="https://github.com/WeblateOrg/website/assets/72026317/9420c116-7cb0-4455-b446-ec1e765e5d4e">

**(2)**
<img width="787" alt="image" src="https://github.com/WeblateOrg/website/assets/72026317/1ff2d87d-6b11-4064-aed4-641a88581a61">

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://weblate.org/fr/
2. Go to https://weblate.org/es/

**Comment by nijel** [comment]
The deploy is not automated, I will trigger it now.

**Comment by khalidbelk** [comment]
> The deploy is not automated, I will trigger it now.

Solved. Thank you !
