### ISSUE TITLE
<pre> tag should remain LTR even in RTL interface

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/website#26]
This is how the <pre> tag looks in RTL context currently:
![screenshot-2017-6-20 weblate](https://user-images.githubusercontent.com/406826/27319491-6e884c84-559a-11e7-9869-63283c61323a.png)

The patch I'm linking to is adding an always ltr in css and it should look like this:
![screenshot-2017-6-20 weblate 1](https://user-images.githubusercontent.com/406826/27319516-8c88efe0-559a-11e7-876e-d4b5ac23b261.png)

**Comment by yarons** [comment]
See #27.

**Comment by nijel** [comment]
Fixed by your patch
