### ISSUE TITLE
(PYL-W0613) Function contains unused argument

### ISSUE THREAD

**Issue by adalbertobrant** [WeblateOrg/website#323]
## Description
An unused argument can lead to confusions. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There are 2 occurrences of this issue in the repository.

payments/dbrouter.py
def db_for_write(self, model, **hints):
**hints is not used at all

payments/dbrouter.py 
def allow_migrate(self, db, app_label, model_name=None, **hints): 
model_name is not used

**Comment by nijel** [comment]
This is part of Django database router API, see https://docs.djangoproject.com/en/3.1/topics/db/multi-db/#database-routers
