### ISSUE TITLE
Needs a bit of contexte

### ISSUE THREAD

**Issue by trebmuh** [WeblateOrg/website#37]
Please, see https://hosted.weblate.org/translate/weblate/master/fr/?checksum=6890950ec5c177fb#comments

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
