### ISSUE TITLE
Missing RTL layout

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/website#43]
Hi,
New **Hosted** Weblate is lacking of some RTL CSS/layout for some languages. Seems the layout is aligned only left.
Example : https://weblate.org/ar/
May be : `text-align: right;` ?
Regards,

**Comment by nijel** [comment]
Probably it needs http://bootstrap.rtlcss.com/

**Comment by BoFFire** [comment]
Yes, just tested that rtlcss Website, seems compliant and for RTL :)

**Comment by nijel** [comment]
The official support in bootstrap seems to be a bit stalled, see https://github.com/twbs/bootstrap/issues/24807

**Comment by BoFFire** [comment]
Unbelievable.

**Comment by nijel** [comment]
I've just pushed new website using https://github.com/PerseusTheGreat/bootstrap-4-rtl, it seems to look better, but for me it's easy to miss something broken here, so feedback is welcome...

**Comment by BoFFire** [comment]
Thank you !
I've checked https://weblate.org/ar/hosting/ were there's a table, it's perfect on Mobile even on Desktop version.
Issue can be closed.
