### ISSUE TITLE
GitHub logo is used as symbol for free software

### ISSUE THREAD

**Issue by Wuzzy2** [WeblateOrg/website#45]
On <https://weblate.org/en/features/> there is a point that says Weblate is free software.
And the symbol used for that is the GitHub logo ...

This isn't right.

Note that GitHub is NOT free software, so using the GitHub logo as symbol for free software is quite ironic. I find it a bit disturbing to see a proprietary web service being used as icon for free software.

Besides, this particular usage of the GitHub logo might (MIGHT!) even be a trademark violation, as the GitHub logo is a trademark as far I know. But IANAL, nor am I an advocate of GitHub. Just saying.

So I suggest to use any other symbol for this point. Something about freedom. Maybe a dove?
On this website you find lots of public domain SVGs:
https://openclipart.org/search/?query=dove

**Comment by nijel** [comment]
The reason is that this icon was easy to find. We're currently using [Font Awesome](https://fontawesome.com/icons) for icons, so any suggestions to improve them are welcome.

PS: Trademark wise it should be okay as it's used to link a project on GitHub.

**Comment by comradekingu** [comment]
Here are some I found
https://fontawesome.com/icons/eye?style=regular better eye
https://fontawesome.com/icons/language?style=solid language
https://fontawesome.com/icons/door-open?style=solid
https://fontawesome.com/icons/linux?style=brands
https://fontawesome.com/icons/handshake?style=regular (collaboration sites?)

**Comment by nijel** [comment]
Thanks for your suggestions! I've chosen something different meanwhile, but I like https://fontawesome.com/icons/hand-holding-heart?style=solid more.

**Comment by comradekingu** [comment]
Other good ones:

Edit:
https://fontawesome.com/icons/bicycle?style=solid
https://fontawesome.com/icons/window-maximize?style=regular
https://fontawesome.com/icons/people-carry?style=solid
https://fontawesome.com/icons/laugh?style=regular
https://fontawesome.com/icons/history?style=solid
https://fontawesome.com/icons/haykal?style=solid
https://fontawesome.com/icons/hat-wizard?style=solid
