### ISSUE TITLE
Make Weblate docs URL localizable in weblate/website string

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/website#452]
https://github.com/WeblateOrg/website/blob/06fd5aee819f9ebc9482f51ff41ee678cca65f77/weblate_web/templates/download.html#L52

Please consider making the URL to documentation translatable to make use of localization. If there is any kind of URL for a content negotiation to automatically set the language, even better.

**Comment by nijel** [comment]
Good point. In Weblate we already have the code to generate a documentation link based on current locale, that should be used here as well.
