### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jorgesumle** [WeblateOrg/website#46]
What's the software license for this project? I think it would be a good idea to add a `COPYING` or `LICENSE` file here.

**Comment by nijel** [comment]
Good point, it should be same as Weblate itself.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
