### ISSUE TITLE
Offer space for dedicate cloud and self-hosted instances to list on weblate.org

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/website#532]
**Is your feature request related to a problem? If so, please describe.**
I believe that help to set-up big translation community, get volunteer translators for random projects and less contributed languages. Currently upto 500 projects available in hosted weblate however there're interesting instances similar https://l10n.opensuse.org but we never know unless use or personally know well about certain product or service.

As a translator side, i get more benefit from https://hosted.weblate.org page to find and get access to unexpected interesting projects that support for localization. Otherhand i see that adds some bonus to weblate platform sustainability 

**Describe the solution you'd like**

Add another tab to https://hosted(newname?).weblate.org page as "hosted" and "dedicated" or https://name.weblate.org/ for it

**Comment by Aikatsui** [comment]
Edits: UI sample changed (if you may already working on this and got idea from it)
             (reason: it takes unwanted space and may annoying to scroll and view when has many projects)
previous sample able to view under "previous UI sample"

**Comment by Aikatsui** [comment]
Děkuju (Thank you) 🥰
1. Can you set project links to open in new tab? otherwise everytime when user click something then it leave the main page
2. Minor enhancement suggestions: discover page still seems doesn't take signed-in translators **regular** attention. page design already good for visitors but the purpose isn't for them, just to active community members (translators). I cannot suggest exact solution and it may need to handle somehow through design or other component adjustment
    -  Everyone usually tap the big "Go Weblate" button and has less attention for upper body sign-in button on home page. may be it's possible to add description (scr 2) to it or change that button to "Sign in" (scr 2)
    - Add discover button to `https://weblate.org/en/user/` page (scr 2)

![image](https://user-images.githubusercontent.com/63988538/114444636-5038e500-9bf9-11eb-86f5-8b5f215f9544.png)

![21766809_1446478052072767_8245428529106869485_n](https://user-images.githubusercontent.com/63988538/114552638-03075280-9c8f-11eb-8762-d7babb52ac04.png)

![ksnip_20210413-165354](https://user-images.githubusercontent.com/63988538/114552701-12869b80-9c8f-11eb-84f4-4a7db39dfec5.png)

**Comment by Aikatsui** [comment]
@nijel can you set this https://github.com/WeblateOrg/weblate/wiki/References page as editable? i like to keep it updated.
https://weblate.openkylin.top/ https://translations.vivaldi.com/

https://weblate.org/en/discover/ (interested parties can use it to publish their own instances)

**Comment by comradekingu** [comment]
@Aikatsui 
I pulled the changes out of the log when the WL equivalent got deleted https://github.com/comradekingu/posts/wiki
Feel free to edit that. :)
Unfortunately it is the one where closed source projects are mixed in with libre ones, which is a total departure from DFSG guidelines.
Vivaldi is somewhere in between btw. :)

**Comment by Aikatsui** [comment]
>Unfortunately it is the one where closed source projects are mixed in with libre ones

It's easy to move FOSS projects to the top. I like to keep a wiki (this or your) updated as awesome-weblate
This definitely useful for everyone to find on-premise instances and sometimes we can apply TM to similar projects (e.g. OS distros, Chat apps) and i forgot to say @nijel to keep weblate's wiki enabled (or didn't come that to mind)

Weblate discover - For Interested parties to add their own instances and they can collect new contributors as well. it's the best place for find on-premise instances very easily. Otherhand, now when someone come to try / self-host weblate, they can see large projects with live proof e.g. opensuse, mattermost etc
Wiki - On-premise instances collection (or the unseen weblate city)

>Feel free to edit that. :)

@comradekingu  Thank you. But I can't edit it. You need to change permission
https://github.com/comradekingu/posts/wiki
