### ISSUE TITLE
feed only has summary

### ISSUE THREAD

**Issue by stbuehler** [WeblateOrg/website#54]
JFYI: I read the old blog through debian planet, but I'm not going to subscribe to a summary feed.

Thanks for your work on weblate anyway.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
