### ISSUE TITLE
What to call "Hosted Weblate"?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#68]
https://hosted.weblate.org
This should be "Log out", which I think the current PR fixes, however the "App" links to "Hosted Weblate"
![Skjermbilde fra 2019-07-16 19 04 17](https://user-images.githubusercontent.com/13802408/61314274-98e12580-a7fc-11e9-8a54-70bc3ff7d860.png)
What gives?

**Comment by nijel** [comment]
The problem is that "Weblate App" is easy to understand, while "Hosted Weblate" seems to be confusing for most (new) users.

**Comment by comradekingu** [comment]
Please noooooooooooooooooo oh_nopes.jpeg2000
While everyone may understand "Weblate app", this _isn't_ actually an app…
Moreover, "Hosted Weblate" is consequentially _in every other instance_ "Hosted Weblate".
Therefore this not only breaks established convention in Weblate, it actually challenges the use of one of the more common words in modern English. Was it meant to be "Weblate cloud" perchance?

(I started typing something semi-related, because I had difficulty putting my displeasure of "Weblate app" to words)
App is not distinguishable from "program" going forwards, where English seems to more commonly employ "application" for computer programs nowadays, it will inevitably use "app" for everything, and then run into a situation where there is no word for light program, where the "program/application version of something is not the app today. Similarly "mail" is about to be both postal mail and e-mail, but there is "snailmail" to replace the former.

This reminds me of when I heard someone describe Facebook as "the new Internet", (meaning "the new web").

**Comment by nijel** [comment]
I'm open to suggestions, what we need:

* Something short
* "Hosted Weblate" really doesn't work for new users, I've heard this feedback several times

I've changed it to "Use Weblate" for now

**Comment by comradekingu** [comment]
I think "Weblate cloud" possibly with "Hosted Weblate Cloud" in a transition period is both understandable and short.

**Comment by nijel** [comment]
I'm not sure about renaming it, my intention was just to make navigation from the website to the application easy to find for new users, what "Use Weblate" button addresses.

Maybe @orangesunny can comment on this?

**Comment by comradekingu** [comment]
@nijel It remains to be seen what users respond better to. I don't really have a dog in this race, but I spent some time trying to solve this for Pootle, resulting in "Pootle cloud".

**Comment by nijel** [comment]
We already have the name and domain and I don't think that "Weblate Cloud" is substantially better to outweigh troubles with renaming. Also I think being slightly different might be better when everybody is in the cloud :-).

**Comment by orangesunny** [comment]
I am thinking about this constantly; Hosted Weblate is so far so good. Will let you know when new ideas will come.

**Comment by fitojb** [comment]
“Weblate-[as-a-service](https://en.wikipedia.org/wiki/As_a_service)”?
