### ISSUE TITLE
Moiré effect in picture when scrolling past

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#69]
https://betaweb.weblate.org/media/images/weblate-html.png
![image](https://user-images.githubusercontent.com/13802408/61315296-bfa05b80-a7fe-11e9-9b5a-c1177c93583b.png)
Alternative fix, link to
https://xkcd.com/1814/ :)

**Comment by nijel** [comment]
The picture was intentionally taken to show moire

**Comment by comradekingu** [comment]
Was the scrolling effect that got to me, but I am happy about it being intentional.
