### ISSUE TITLE
Blog: Borders for social buttons

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#70]
https://betaweb.weblate.org/en/news/archive/weblate-371/
![Skjermbilde fra 2019-07-16 19 29 42](https://user-images.githubusercontent.com/13802408/61316008-4dc91180-a800-11e9-9f61-a13e656fe101.png)
![Skjermbilde fra 2019-07-16 19 29 54](https://user-images.githubusercontent.com/13802408/61316015-50c40200-a800-11e9-86b0-ce9c7219f7dd.png)

Don't know how annyoing I am getting with these, but I think
![image](https://user-images.githubusercontent.com/13802408/61316069-781acf00-a800-11e9-86a9-51672a9a3ead.png)
would look better, and more consistent

**Comment by nijel** [comment]
I tend to prefer the bordered version here. In the end this is what we want people to do with the posts in our blog.

**Comment by comradekingu** [comment]
Everything else is nice and round, and then those are different from the other social buttons, and square.
If they were green and then went to that dark gray colour on mouseover it would be how I would imagine it worked if they weren't there.

**Comment by nijel** [comment]
Okay, I've made them round as well.
