### ISSUE TITLE
Blog: Social buttons top _and_ bottom?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#71]
https://betaweb.weblate.org/en/news/archive/weblate-371/
![Skjermbilde fra 2019-07-16 19 29 42](https://user-images.githubusercontent.com/13802408/61316190-b4e6c600-a800-11e9-94b0-2c1b6f2dec79.png) x2
Other one is "with friends". Is there some click-through increase on doing it twice?

**Comment by nijel** [comment]
The idea is to have this available directly on top and also after reading the article. With short articles it looks indeed as not needed, it's mostly targeted at longer posts to make it easy to share after you read them.
