### ISSUE TITLE
Blog: Staggered top level between articles

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#72]
![image](https://user-images.githubusercontent.com/13802408/61317090-94b80680-a802-11e9-8a2f-70c47c3b0aa0.png)

Could be intentional, but seems a bit strange to me.

**Comment by nijel** [comment]
This is caused by different image sizes - the articles are aligned on text. For future posts the image sizes should be consistent and maybe we should even adjust past images...

**Comment by nijel** [comment]
I've just fixed the images.
