### ISSUE TITLE
Hitbox for language selector misaligned

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#73]
https://betaweb.weblate.org/en/
![image](https://user-images.githubusercontent.com/13802408/61319846-71905580-a808-11e9-87b6-2f412d9e3d8b.png)

Aside from the visuals, the whole visual button should be covered.
Leftclick and then release after a while to see the box.

**Comment by nijel** [comment]
Fixed by 1d8c6b4680acb2dcdbb33504911749513a5dd76f
