### ISSUE TITLE
Redesign not updated from master?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#76]
Noticed the already fixed "GitLab" hasn't made it into the Redesign branch 

https://github.com/WeblateOrg/website/blob/70249ed63c8343d2d375b79bd17d13d29dc16ea0/weblate_web/templates/features.html#L152

https://github.com/WeblateOrg/website/blob/70249ed63c8343d2d375b79bd17d13d29dc16ea0/weblate_web/templates/features.html#L152

https://github.com/WeblateOrg/website/blob/70249ed63c8343d2d375b79bd17d13d29dc16ea0/locale/en_GB/LC_MESSAGES/django.po#L843

**Comment by nijel** [comment]
It's possible that some recent changes from master are missing, the redesign was started somewhere in March and the texts are coming from that time. I've tried to bring back updated strings manually, but it's easy to miss something.

**Comment by comradekingu** [comment]
OK :)
