### ISSUE TITLE
Lineshifted text in browse documentation button

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#78]
https://betaweb.weblate.org/en/contribute/
![Skjermbilde fra 2019-07-17 16 50 48](https://user-images.githubusercontent.com/13802408/61385782-57f81800-a8b3-11e9-8cac-b28430b70a1e.png)

**Comment by nijel** [comment]
This happens if text doesn't fit into button, I don't see better approach.

**Comment by comradekingu** [comment]
Just "Documentation"?

**Comment by nijel** [comment]
That might address it for this particular button and English, but generally the problem will stay there.

![Screenshot_2019-07-18 Bidra til Weblate](https://user-images.githubusercontent.com/212189/61440486-f3d16480-a943-11e9-80b4-738efb01f6ee.png)

**Comment by comradekingu** [comment]
![image](https://user-images.githubusercontent.com/13802408/61440954-fa141080-a944-11e9-9985-41722776afa9.png)
Got rid of the middle bit and scaled the text up.
With the text staying the same, I think that is ideal.
