### ISSUE TITLE
Missing row of pixels in speech-bubble

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#83]
![bilde](https://user-images.githubusercontent.com/13802408/61556590-751f1900-aa62-11e9-8a09-0f6b06b3442c.png)

If it is meant to wrap, should be the other way around. Could be intentional?

**Comment by nijel** [comment]
In which browser do you see that? It works fine for me in all browsers I've tested...

**Comment by comradekingu** [comment]
FF 68 and Epipany. Though I forgot what page it was on.

**Comment by comradekingu** [comment]
https://betaweb.weblate.org/en/about/
OK, so it is actually a scaling issue. Looks good at 100%, but then not at various steps beyond that
1920x1200 screen
