### ISSUE TITLE
Add link to translation project

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/website#832]
So people can add id of their language after **/** at the end of link in the editor
https://github.com/WeblateOrg/website/blob/8e21d67cd80b4f659f47e94aacfc3c955ab59f11/weblate_web/templates/snippets/main-menu.html#L19

**Comment by nijel** [comment]
The link to https://weblate.org/contribute/#translate is in the language selector. Maybe this is what you are looking for?
