### ISSUE TITLE
Floating translation field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#87]
https://betaweb.weblate.org/en/features/

Features this image leftwards

![bilde](https://user-images.githubusercontent.com/13802408/61576510-45602780-aadb-11e9-97c3-dc618abaf8d0.png)

---

![bilde](https://user-images.githubusercontent.com/13802408/61576587-0ed6dc80-aadc-11e9-83e3-f64044a0ba53.png)

---

70%
![bilde](https://user-images.githubusercontent.com/13802408/61576589-1c8c6200-aadc-11e9-9757-27e841ea396d.png)

**Comment by nijel** [comment]
Apparently I've messed up the CSS for this page by some changes, it used to be okay.

**Comment by nijel** [comment]
Okay, it was HTML messed up recently. Fixed now.
