### ISSUE TITLE
Unexplained asterix fields in donation form

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#90]
https://weblate.org/en/payment/cfd43415-65ba-474e-8175-9c8313db0e1e/edit/

For example "Company or individual name*"
Are those optional, am I missing something?

**Comment by nijel** [comment]
The asterisk marked fields are required. It probably could be optional up to some amount (AFAIR it's something like 200 EUR), but I would have to check with my tax advisor (and it would complicate the process as I'd have to issue different tax receipt in that case).

Anyway on new web the asterisk is gone:

https://betaweb.weblate.org/en/payment/cfd43415-65ba-474e-8175-9c8313db0e1e/edit/

**Comment by comradekingu** [comment]
My bad, didn't notice I was on the old page.

**Comment by nijel** [comment]
The payment gateway is hardcoded on `weblate.org` as that's the URL registered at the service.
