### ISSUE TITLE
List of languages not translated in donation form

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#91]
https://betaweb.weblate.org/nb/payment/cfd43415-65ba-474e-8175-9c8313db0e1e/edit/

Should use the ones from Weblate, or the debian ISO ones from Hosted?

**Comment by nijel** [comment]
That's list of countries not languages and we don't have that in Weblate ;-). It's using [django-countries](https://github.com/SmileyChris/django-countries) and they have own localization.

**Comment by comradekingu** [comment]
@nijel I was thinking of the languages. Maybe https://hosted.weblate.org/projects/iso-codes/iso-3166-1/ could be used for countries? The easiest solution would be for me to just fix it in django-countries, as I imagine lots of other projects benefit from that.

I noticed django-countries has
https://github.com/SmileyChris/django-countries/blob/master/django_countries/locale/de/LC_MESSAGES/django.po
but https://betaweb.weblate.org/de/payment/cfd43415-65ba-474e-8175-9c8313db0e1e/edit/ also uses the English names.

**Comment by nijel** [comment]
Thanks for pointing out, it was misconfiguration on the web server.
