### ISSUE TITLE
Landing page flow

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#93]
![bilde](https://user-images.githubusercontent.com/13802408/61639837-8489a680-ac9c-11e9-8239-32223998fdc4.png)

The top right and the mid centre one do the same thing.
The top right one is truncated into
![bilde](https://user-images.githubusercontent.com/13802408/61640019-e0ecc600-ac9c-11e9-853b-8e70d9a5fa82.png)
at low resolutions, so maybe it could be dropped all-together?

"Exploring all features" is also a bit out of place, seeing as some of the features are listed below,
and there is a logical "explore all features there".

That fits the categories a bit better:

1. Features
(is now "Try Weblate") Download
2.Pricing
Contribute
Donate
Get help
Blog
About
Docs 

The users and supporters is a bit too prominent, even before the presentation of what Weblate actually is. I would put it below the "Go to pricing", as it ensures the user there are more known projects onboard.

I think putting "Try Weblate" and "See all projects" should open in new tabs, otherwise it sends people intent on purchasing and understanding what Weblate is, away from the purchase plans and info about Weblate.

Am I missing some other intention here?

**Comment by nijel** [comment]
The "Use Weblate" button is on all pages, that's why it's in the top navigation. I think it's okay like it's now.

I've moved the projects listing a bit lower, you're right that this doesn't have to that visible.

As for the new tab, I don't like such behavior, so I usually don't use that :-).
