### ISSUE TITLE
New website does not have legal info?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#97]
Was looking for something like https://pyra-handheld.com/boards/pages/legal/

**Comment by nijel** [comment]
We have https://betaweb.weblate.org/terms/

That page looks like the impressum, which is required in Germany, however we don't have such law here and I don't think it adds much value to users.

**Comment by comradekingu** [comment]
It does instil some confidence in parting with money on the Internet. A lot of projects don't have a company behind it, so there is some free goodwill right there.

A similar use-case is figuring out whether one can write off a donation according to ones local laws if it is an org, a company, or a charitable operation. I would expect to see it in https://betaweb.weblate.org/nb/about/ because it is the kind of thing you need if you want to present the idea of using Weblate in a bigger organization.

The other concern is the "what is the fastest way to contact someone with the least amount of effort required". Could go either way I suppose, but right now it is support@WL when that is the premium support address. Another way is getting onto the bug-tracker to find the problem escalation e-mail.

**Comment by nijel** [comment]
Good point, there should be some easy to find contact information on the about page.

Weblate (still) doesn't have a company behind it, so legally it's just me. This will have to change at some point, but I hate paperwork, so I postpone this as much as possible :-).
